Repository Capstone-Buddies/qflare-back-end, pull requests merged in 2024-06, with the labels that each got.

#12 10 update doc for register and login
  .env.example
  API Documentation.md
Labels: documentation

#13 8 develop all dummy endpoint
  .env.example
  src/controllers/auth.controller.ts
  src/controllers/quiz.controller.ts
  src/controllers/user.controller.ts
  src/drizzle/schema.ts
  src/index.ts
  src/models/auth.model.ts
  src/models/user.model.ts
  src/routes/auth.route.ts
  src/routes/quiz.route.ts
  src/routes/user.route.ts
Labels: documentation

#15 14 develop request validation for register and login
  API Documentation.md
  src/controllers/auth.controller.ts
  src/drizzle/schema.ts
  src/middlewares/requestValidation.middleware.ts
  src/routes/auth.route.ts
  src/routes/quiz.route.ts
  src/routes/user.route.ts
  src/zod/schemas/authRoute.ts
  src/zod/schemas/expressRequest.ts
Labels: enhancement

#17 11 update register and login
  API Documentation.md
  src/constants.ts
  src/controllers/auth.controller.ts
  src/controllers/quiz.controller.ts
  src/controllers/user.controller.ts
Labels: bug, enhancement

#20 Integrate auth and request validation middleware
  src/middlewares/auth.middleware.ts
  src/middlewares/requestValidation.middleware.ts
  src/routes/user.route.ts
  src/zod/schemas/expressRequest.ts
Labels: enhancement

#26 25 develop get quizeshistories
  API Documentation.md
  src/controllers/quiz.controller.ts
  src/models/quiz.model.ts
  src/routes/quiz.route.ts
Labels: enhancement

#28 27 develop get quizeshistorieshistoryidanswers
  API Documentation.md
  package.json
  src/controllers/quiz.controller.ts
  src/models/quiz.model.ts
  src/routes/quiz.route.ts
  src/zod/schemas/quizRoute.ts
Labels: documentation, enhancement

#31 30 update POST/ register add school origin
  API Documentation.md
  src/controllers/auth.controller.ts
  src/drizzle/dummyData/users.ts
  src/drizzle/schema.ts
  src/middlewares/auth.middleware.ts
  src/models/user.model.ts
  src/zod/schemas/authRoute.ts
Labels: enhancement

#32 29 develop get usersmy profile
  API Documentation.md
  src/controllers/user.controller.ts
  src/drizzle/schema.ts
  src/middlewares/auth.middleware.ts
Labels: documentation, enhancement

#37 35 integrate ml model
  .env.example
  API Documentation.md
  README.md
  src/constants.ts
  src/controllers/quiz.controller.ts
  src/drizzle/schema.ts
  src/middlewares/auth.middleware.ts
  src/models/auth.model.ts
  src/models/quiz.model.ts
  src/models/user.model.ts
  src/routes/quiz.route.ts
  src/zod/schemas/authRoute.ts
  src/zod/schemas/quizRoute.ts
Labels: documentation, enhancement

#39 36 optional develop put usersmy profile
  API Documentation.md
  package.json
  src/config/storage.config.ts
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/drizzle/dummyData/users.ts
  src/models/user.model.ts
  src/routes/user.route.ts
Labels: enhancement

#40 38 setup docker
  .dockerignore
  .env.example
  Dockerfile
  README.md
  package.json
  src/config/storage.config.ts
  src/controllers/auth.controller.ts
  src/controllers/quiz.controller.ts
  src/controllers/user.controller.ts
  src/middlewares/requestValidation.middleware.ts
  src/models/auth.model.ts
  src/models/quiz.model.ts
  src/models/user.model.ts
  src/routes/auth.route.ts
  src/routes/quiz.route.ts
  src/routes/user.route.ts
  src/zod/schemas/expressRequest.ts
  src/zod/schemas/quizRoute.ts
  tsconfig.json
Labels: documentation, enhancement
